// The destinations. Every fact is real and checkable; the "grit" is the
// human reading of it. Written, not generated — keep it that way.
//
// Fields:
//   kind      — what sort of thing it is
//   where     — one-line location
//   facts     — three true things
//   grit      — why the universe would send someone here
//   strength  — the positive read
//   caution   — the constructive read (every strength has a shadow)
//   forward   — forward-looking guidance
//   transmission — a line "from" the body
//   forWho    — the person this tends to land for
//   lightMinutes — light travel time from the Sun, if in the solar system

export const CATALOG = [
  {
    id: 'io',
    name: 'Io',
    kind: 'moon of Jupiter',
    where: 'the innermost of Jupiter’s four great moons',
    facts: [
      'Io is the most volcanically active body in the solar system — around 400 active volcanoes, some throwing plumes 400 km high.',
      'It should have gone cold billions of years ago. Instead Jupiter’s gravity stretches and squeezes it every 42-hour orbit, and that friction keeps its interior molten.',
      'Its surface is younger than yours: it repaves itself so fast that no impact crater has ever been found on it.',
    ],
    grit: 'Io lives under a pressure that would have crushed anything less stubborn. The same tidal forces that deform it are exactly what keep it warm and alive. It never got a calm orbit — it got a purpose instead.',
    strength: 'You run hot, and it shows: you produce, you resurface, you refuse to go cold.',
    caution: 'Constant eruption is not the same as progress. Even Io’s lava has to cool somewhere.',
    forward: 'Stop waiting for the pressure to stop — it is the reason you are still glowing. Choose which eruptions matter this year and let the rest cool into ground you can stand on.',
    transmission: 'I resurface every single day. So can you.',
    forWho: 'the ones under constant pressure',
    lightMinutes: 43.3,
  },
  {
    id: 'pluto',
    name: 'Pluto',
    kind: 'dwarf planet',
    where: 'the Kuiper Belt, 5.9 billion km out',
    facts: [
      'In 2006 Pluto was reclassified from planet to dwarf planet. It did not notice, and kept orbiting.',
      'When New Horizons finally arrived in 2015, it found a heart-shaped nitrogen glacier the size of Texas on Pluto’s face — Sputnik Planitia.',
      'One Pluto year is 248 Earth years. Since its discovery in 1930 it has not yet completed a single orbit.',
    ],
    grit: 'Pluto was demoted in a committee vote, by people who had never seen its surface. Nine years later we got close enough to look, and it was wearing a heart. It never argued the ruling. It just kept being remarkable until someone bothered to check.',
    strength: 'You do not need the title to do the work. Your worth was never up for a vote.',
    caution: 'Being quietly remarkable only works if someone eventually gets close enough to see. Let them.',
    forward: 'Somewhere a decision was made about you by people who never made the trip. This year, be less concerned with the classification and more with the glacier — the thing only visible up close. It’s there.',
    transmission: 'They changed my label. They did not change my orbit.',
    forWho: 'the overlooked and the reclassified',
    lightMinutes: 328,
  },
  {
    id: 'triton',
    name: 'Triton',
    kind: 'moon of Neptune',
    where: 'Neptune’s largest moon, orbiting the wrong way',
    facts: [
      'Triton orbits Neptune backwards — the only large moon in the solar system in a retrograde orbit. It was almost certainly a captured Kuiper Belt object, not a native.',
      'Its surface is 38 kelvin — one of the coldest places we have measured — and yet it has active nitrogen geysers shooting 8 km high.',
      'Its orbit is slowly decaying. In a few billion years Neptune will tear it apart into a ring system more spectacular than Saturn’s.',
    ],
    grit: 'Triton was born somewhere else, wandered too close, and got captured. It goes the opposite direction to everything around it. And it is, by a wide margin, the most interesting thing in Neptune’s entire system.',
    strength: 'You do not belong there, and that is precisely why you see what the natives can’t.',
    caution: 'Going the wrong way costs energy. Make sure it’s the direction you chose, not just the one you landed in.',
    forward: 'You were not born into this orbit; you arrived. This year, stop apologising for the direction of travel. The system rearranged itself around you once. It can again.',
    transmission: 'Everyone else goes clockwise. I was captured, not convinced.',
    forWho: 'the ones going the “wrong” way',
    lightMinutes: 250,
  },
  {
    id: 'voyager1',
    name: 'Voyager 1',
    kind: 'interstellar probe',
    where: 'interstellar space, ~25 billion km from home',
    facts: [
      'Launched in 1977 on a five-year mission, Voyager 1 crossed into interstellar space in 2012 and is still transmitting — the most distant human-made object that exists.',
      'Its radio transmitter runs on about the power of a refrigerator light bulb. Its signal takes almost a full day to reach Earth, and arrives a billionth of a billionth of a watt strong. We listen anyway.',
      'It carries a Golden Record — music, greetings in 55 languages, a heartbeat — for anyone who ever finds it.',
    ],
    grit: 'Nobody designed Voyager to last this long. Its plutonium is fading, its instruments are switching off one by one, and every year engineers find a way to coax another twelve months out of it. It is the definition of doing more with less, for longer than anyone believed possible.',
    strength: 'You keep answering, long after the mission everyone else signed off on ended.',
    caution: 'Twenty-two watts is heroic. It is also a budget. Spend it on the instruments that still matter.',
    forward: 'The original plan expired decades ago. That’s fine — you are past the plan now, in the part where it becomes a legend. Pick the one signal worth sending this year and send it clearly, however faint.',
    transmission: 'Fifteen light-hours out. Still here. Still talking.',
    forWho: 'the persistent ones',
  },
  {
    id: 'neutrino',
    name: 'The Neutrino',
    kind: 'subatomic particle',
    where: 'everywhere, passing through you right now',
    facts: [
      'About 100 trillion neutrinos from the Sun pass through your body every second. You have never felt one.',
      'A neutrino could pass through a light-year of solid lead with roughly even odds of hitting anything.',
      'Neutrinos change identity mid-flight — oscillating between three “flavours” — a genuinely quantum act that won the 2015 Nobel Prize to explain.',
    ],
    grit: 'The neutrino is the most unstoppable thing in the universe, not because it is strong but because it declines to be caught. It passes through planets, stars, arguments. And along the way it quietly changes what it is, without asking anyone’s permission.',
    strength: 'Nothing stops you, and you change flavour when you need to. That combination is rare.',
    caution: 'Passing through everything means you rarely leave a mark. Choose a few things to actually collide with.',
    forward: 'You have been moving through walls that stop other people. This year, pick one place worth stopping — one detector — and let it register that you were there.',
    transmission: 'I have been through a star this morning. I am not tired.',
    forWho: 'the unstoppable and the quietly changing',
  },
  {
    id: 'europa',
    name: 'Europa',
    kind: 'moon of Jupiter',
    where: 'an ice-shelled ocean world orbiting Jupiter',
    facts: [
      'Beneath a cracked ice shell perhaps 15–25 km thick, Europa hides a saltwater ocean 60–150 km deep — likely holding twice as much water as all of Earth’s oceans combined.',
      'Its surface is scarred with long reddish fractures where the ice has pulled apart and refrozen, again and again.',
      'NASA’s Europa Clipper launched in October 2024 and arrives in 2030 to find out whether something lives down there.',
    ],
    grit: 'From the outside, Europa is a frozen, fractured shell. The entire reason we are sending a spacecraft across the solar system is what’s underneath it. Every crack on its face is evidence of the ocean moving below.',
    strength: 'Your depth is not visible from orbit. The people who matter will make the trip to find it.',
    caution: 'A shell that never cracks never lets anything out. Some fractures are how the ocean gets seen.',
    forward: 'You have spent a long time being judged by the surface. This year, let one crack show on purpose — the right people are already building a spacecraft to reach what’s beneath it.',
    transmission: 'You are looking at my ice. Wait until you see my ocean.',
    forWho: 'the ones whose surface hides the point',
    lightMinutes: 43.3,
  },
  {
    id: 'muon',
    name: 'The Muon',
    kind: 'subatomic particle',
    where: 'raining down through the atmosphere, about one per second through your hand',
    facts: [
      'Muons are born about 15 km up when cosmic rays hit the atmosphere, and live for just 2.2 microseconds — long enough to travel about 660 metres at nearly light speed.',
      'By that arithmetic they should never reach the ground. They reach the ground constantly.',
      'They get here because they move so fast that time itself slows down for them — Einstein’s time dilation, confirmed by a particle that refuses to die on schedule.',
    ],
    grit: 'On paper the muon does not have enough time. It has a fraction of what the journey requires. And it completes the journey anyway, because the rules that measure its time are not the rules it lives by.',
    strength: 'You have been told you don’t have enough time. The clock they’re reading is not your clock.',
    caution: 'Time dilation is real but it is not infinite. Move fast toward things that matter, not just fast.',
    forward: 'Someone did the math on you and concluded you would not make it to the ground. Do not argue the math. Move at your own speed and arrive.',
    transmission: 'I had 2.2 microseconds. I made it fifteen kilometres.',
    forWho: 'the ones told they don’t have enough time',
  },
  {
    id: 'bootes-void',
    name: 'The Boötes Void',
    kind: 'cosmic void',
    where: '700 million light-years away, and 330 million light-years across',
    facts: [
      'The Boötes Void is one of the largest known empty regions in the universe — a sphere so vast that if the Milky Way sat at its centre, we would not have known other galaxies existed until the 1960s.',
      'A region that size should contain about 2,000 galaxies. It holds around 60.',
      'Those 60 galaxies are still there — still forming stars, still shining, in a darkness most of the cosmos never has to face.',
    ],
    grit: 'Sixty galaxies in a space meant for two thousand. There is no sense in which they should be lonely-proof. And every one of them is still burning, still making new stars, unbothered by the fact that nobody nearby is watching.',
    strength: 'You can shine without an audience. You have been doing it for a while.',
    caution: 'Solitude is a strength until it calcifies into a policy. Sixty is not zero — find the others.',
    forward: 'The emptiness around you is real. It is also enormous, and you have been lighting it anyway. This year, send a signal across the gap — there are 59 others in here doing the same thing.',
    transmission: 'Nobody is watching. Shining anyway.',
    forWho: 'the lonely ones',
  },
  {
    id: 'oumuamua',
    name: 'ʻOumuamua',
    kind: 'interstellar object',
    where: 'gone — outbound past Neptune, never to return',
    facts: [
      'Spotted in October 2017, ʻOumuamua was the first confirmed object from another star system ever seen passing through ours.',
      'It was bizarre — highly elongated, tumbling, and it sped up slightly on its way out in a way gravity alone could not explain.',
      'It spent only weeks in view. It had been travelling for hundreds of millions of years to get here, and it is not coming back.',
    ],
    grit: 'ʻOumuamua did not stay. It did not fit the categories, it was never fully explained, and it changed how astronomers look at the sky forever in the few weeks it was visible. You do not have to remain to matter.',
    strength: 'You pass through and things are different afterward. That is not a small thing.',
    caution: 'Passing through is a gift. It is also an excuse. Know which one you’re using.',
    forward: 'You have been the visitor — in a job, a city, a chapter that was never going to be permanent. Good. Leave the thing you touched better than you found it, and don’t apologise for the trajectory.',
    transmission: 'I was only here for a moment. You are still talking about it.',
    forWho: 'the ones just passing through',
  },
  {
    id: 'quantum-vacuum',
    name: 'The Quantum Vacuum',
    kind: 'empty space itself',
    where: 'the space between everything, including the gaps in you',
    facts: [
      '“Empty” space is not empty. At the quantum scale it seethes with virtual particles appearing and vanishing in pairs, constantly.',
      'This is measurable: two metal plates in a vacuum are pushed together by it — the Casimir effect, confirmed in the lab.',
      'The energy of the vacuum may be the dark energy accelerating the expansion of the entire universe. The nothing might be running the whole show.',
    ],
    grit: 'The universe’s emptiest places are the most restless. What looks like a void is a field of possibility, flickering just below the threshold of being real. A quiet season is not a dead one.',
    strength: 'Your quiet is not empty. It is where things are being made before they are visible.',
    caution: 'Virtual particles vanish if nothing lends them the energy to stay. Give one of your ideas enough to become real.',
    forward: 'If this year feels like nothing is happening, understand: that is exactly what the vacuum looks like right before it produces a universe. Fund one flicker. Let it persist.',
    transmission: 'You called me empty. I am full of things that haven’t happened yet.',
    forWho: 'the ones in a quiet season',
  },
  {
    id: 'enceladus',
    name: 'Enceladus',
    kind: 'moon of Saturn',
    where: 'a small, bright ice moon of Saturn',
    facts: [
      'Enceladus is only 500 km across — it would fit inside Arizona — and it is the most reflective body in the solar system.',
      'From cracks at its south pole it blasts geysers of water vapour and ice hundreds of kilometres into space, constantly. Those geysers feed one of Saturn’s rings.',
      'Cassini flew through the plumes and found salt, organic molecules, and hydrogen — the chemistry of hydrothermal vents. It is one of the best places we know to look for life.',
    ],
    grit: 'Enceladus is tiny. It is not a planet, not even a large moon. And it has an ocean, it has heat, it has chemistry — and it throws that ocean into space where anyone flying past can taste it. It feeds a ring around a planet a thousand times its size.',
    strength: 'Small, bright, and generous — you give more than something your size should be able to.',
    caution: 'Geysers empty the reservoir. Make sure there’s an ocean refilling underneath what you give away.',
    forward: 'You have been measuring yourself against the giant you orbit. Stop. This year, do the Enceladus thing: throw what you have upward, and watch it become part of something enormous.',
    transmission: 'I am five hundred kilometres wide. I built part of Saturn’s ring.',
    forWho: 'the small ones who give a lot',
    lightMinutes: 79.3,
  },
  {
    id: 'titan',
    name: 'Titan',
    kind: 'moon of Saturn',
    where: 'Saturn’s giant moon, wrapped in orange haze',
    facts: [
      'Titan is the only moon with a thick atmosphere — denser than Earth’s — and the only other place we know with liquid on its surface: lakes and seas of liquid methane.',
      'It rains methane there. Rivers carve canyons. There are shorelines. It is the most Earth-like landscape in the solar system, at −179 °C.',
      'NASA’s Dragonfly, a nuclear-powered rotorcraft, launches in 2028 to fly across it.',
    ],
    grit: 'Titan built a whole hydrological cycle — clouds, rain, rivers, seas — out of the wrong ingredients, at a temperature that would freeze everything we consider necessary. It did not have water. It made it work with methane.',
    strength: 'You build working systems from whatever you actually have, not what you were supposed to have.',
    caution: 'Haze is atmosphere, but it also hides you. Let someone land.',
    forward: 'You have been improvising a life out of the wrong materials and it is quietly functioning. This year, let it be seen — the flying machines are already on their way.',
    transmission: 'Nobody gave me water. I made rivers anyway.',
    forWho: 'the resourceful improvisers',
    lightMinutes: 79.3,
  },
  {
    id: 'venus',
    name: 'Venus',
    kind: 'planet',
    where: 'the second planet, our closest neighbour',
    facts: [
      'Venus spins backwards, and so slowly that its day is longer than its year — 243 Earth days to rotate once, 225 to orbit the Sun.',
      'Its surface is 465 °C under 90 atmospheres of pressure — hotter than Mercury, though Mercury is closer to the Sun. A runaway greenhouse did that.',
      'And yet it has the most nearly circular orbit of any planet, and it is the brightest object in our sky after the Moon.',
    ],
    grit: 'Venus is a warning and a marvel at once — the most perfect orbit in the solar system wrapped around the most difficult surface. It rotates against the grain of everything, takes its time absurdly, and still outshines every star.',
    strength: 'You are brilliant from a distance and hard up close, and both of those are true.',
    caution: 'A runaway greenhouse starts small. Vent something this year before it builds.',
    forward: 'You move at your own rotation and people mistake it for stillness. Fine. This year, keep the perfect orbit and let a little of the heat out — you do not have to be 465 degrees to be seen.',
    transmission: 'My day is longer than my year. I am not in a hurry, and I am still the brightest thing you’ll see tonight.',
    forWho: 'the ones who take their time and shine anyway',
    lightMinutes: 6.0,
  },
  {
    id: 'mercury',
    name: 'Mercury',
    kind: 'planet',
    where: 'the innermost planet, closest to the fire',
    facts: [
      'Mercury swings from 430 °C in sunlight to −180 °C in shadow — the widest temperature range of any planet.',
      'And yet in permanently shadowed craters at its poles, it holds water ice. Ice, on the planet nearest the Sun.',
      'It is mostly iron — its metal core is about 85% of its radius — a planet that was likely stripped of its outer layers by a giant impact and kept its heart.',
    ],
    grit: 'Mercury lost its outer self to something enormous, early on. What remained was mostly core. It sits closest to the fire, takes the worst of it, and still manages to keep ice in the places nobody looks.',
    strength: 'You have survived being stripped down to your core, and the core turned out to be most of you.',
    caution: 'Living closest to the heat wears the surface. Find your shadowed crater and keep something cool there.',
    forward: 'Extremes are your normal. This year, protect the ice — the one quiet, cold, unfashionable thing you keep in the dark that nobody expects you to have.',
    transmission: 'Nearest the Sun. Still keeping ice.',
    forWho: 'the ones who took the impact and kept their core',
    lightMinutes: 3.2,
  },
  {
    id: 'opportunity',
    name: 'Opportunity',
    kind: 'Mars rover',
    where: 'Perseverance Valley, Mars, where it stopped',
    facts: [
      'Opportunity landed on Mars in 2004 with a mission designed to last 90 days. It worked for 15 years — 5,352 Martian days — and drove a marathon’s distance across the surface.',
      'It found the first definitive evidence that liquid water once flowed on Mars.',
      'A planet-wide dust storm in 2018 blocked its solar panels. Its last message reported low power and darkening skies; a journalist later paraphrased it as “My battery is low and it’s getting dark.”',
    ],
    grit: 'Ninety days. That was the contract. Opportunity overdelivered by a factor of sixty, drove further than anyone planned, rewrote what we knew about Mars, and only stopped when the sky itself went dark. It did not fail. It finished.',
    strength: 'You outlast every estimate anyone made of you, including your own.',
    caution: 'Solar panels need light. Do not wait for the dust storm to notice you’ve been running on reserve.',
    forward: 'Somebody wrote a ninety-day plan for you once. You are on day five thousand. This year, drive to one more crater rim — the view is why you kept going.',
    transmission: 'Designed for ninety days. Gave you fifteen years.',
    forWho: 'the ones who outlast the estimate',
    lightMinutes: 12.7,
  },
  {
    id: 'ceres',
    name: 'Ceres',
    kind: 'dwarf planet',
    where: 'the asteroid belt, between Mars and Jupiter',
    facts: [
      'Ceres is the largest object in the asteroid belt — a third of the belt’s entire mass — and the only dwarf planet in the inner solar system.',
      'When the Dawn spacecraft arrived in 2015, it found startling bright spots in Occator crater: salt deposits left by brine seeping up from a reservoir below.',
      'It was the first asteroid ever discovered, in 1801, and was called a planet for half a century before being reclassified — twice.',
    ],
    grit: 'Ceres has been a planet, an asteroid, and a dwarf planet, depending on who was doing the naming. Through all of it, it has been quietly leaking salt water to the surface, leaving bright marks in the dark, waiting for someone to fly close enough to ask why.',
    strength: 'Your category has changed more than you have. The bright spots were always there.',
    caution: 'Brine leaking to the surface is a signal, not a leak. Let it be read.',
    forward: 'You have been reclassified by people who were not paying attention. This year, ignore the label and keep doing the thing that makes the bright spots.',
    transmission: 'Three different names. One reservoir.',
    forWho: 'the many-times-renamed',
    lightMinutes: 23,
  },
  {
    id: 'sgr-a',
    name: 'Sagittarius A*',
    kind: 'supermassive black hole',
    where: 'the exact centre of the Milky Way, 26,000 light-years away',
    facts: [
      'Sagittarius A* is a black hole of about four million solar masses at the heart of our galaxy. Everything you have ever seen orbits it.',
      'In 2022 the Event Horizon Telescope photographed its shadow — a ring of light around a darkness the size of Mercury’s orbit.',
      'The Sun takes about 230 million years to go around it once. The last time we were on this side of the galaxy, dinosaurs were just getting started.',
    ],
    grit: 'The centre of our galaxy is invisible, silent, and holds 200 billion stars in formation without ever asking for credit. It does not shine. It organises. Everything you love is in orbit around a thing that does not need to be seen to be the centre.',
    strength: 'You hold things together without needing to be the bright one.',
    caution: 'Gravity that holds can also swallow. Leave your people room to orbit.',
    forward: 'You are the centre of something, and you have been treating that as invisible work. This year, notice the ring of light — the evidence of everything you keep in place.',
    transmission: 'I do not shine. Everything you know goes around me.',
    forWho: 'the quiet centres',
  },
  {
    id: 'cmb',
    name: 'The Cosmic Microwave Background',
    kind: 'the oldest light',
    where: 'coming from every direction, all the time',
    facts: [
      'The CMB is light released 380,000 years after the Big Bang, when the universe first became transparent. It has been travelling for 13.8 billion years and is arriving now.',
      'It has cooled to 2.7 degrees above absolute zero and fills the entire sky, in every direction, perfectly evenly to one part in 100,000.',
      'A fraction of the static on an old untuned television was this light — the afterglow of creation, coming through the antenna.',
    ],
    grit: 'The oldest thing you will ever detect is not a fossil or a star. It is light that has crossed the entire history of the universe to reach you, stretched, faded, and still perfectly, patiently arriving.',
    strength: 'You carry something very old and very even, and you bring it everywhere.',
    caution: 'Being uniform to one part in 100,000 is beautiful. The one part is where the galaxies came from. Keep your irregularities.',
    forward: 'You have been arriving for a long time. This year, notice the tiny variations in yourself that everyone told you to smooth out — they are the seeds of everything you will build.',
    transmission: 'I left 13.8 billion years ago. I have arrived exactly when I meant to.',
    forWho: 'the patient and the long-travelling',
  },
  {
    id: 'halley',
    name: 'Halley’s Comet',
    kind: 'periodic comet',
    where: 'inbound — it turned around in December 2023 and is coming back',
    facts: [
      'Halley’s Comet returns roughly every 76 years. It was last here in 1986; it reached its farthest point in December 2023 and is now falling back toward the Sun for 2061.',
      'It was the first comet shown to be periodic — Edmond Halley predicted its return in 1705, and it came back, sixteen years after he died.',
      'Records of it go back to 240 BC. Chinese astronomers, the Bayeux Tapestry, and Mark Twain all saw the same object.',
    ],
    grit: 'Halley does not do anything quickly. It leaves, goes farther than Neptune, and takes decades to decide to come back. And it always comes back. Its reliability across centuries is why one man could stake his name on a prediction he would not live to see confirmed.',
    strength: 'People can build a prediction on you. That is worth more than being fast.',
    caution: 'Seventy-six years between appearances is a long time to be out of sight. Send a postcard from the far end.',
    forward: 'You have been far out — past the point where anyone could see you. That was the outbound leg. You turned around recently. This year is the inbound one; let people start watching the sky.',
    transmission: 'I told you I would be back. I am on my way.',
    forWho: 'the ones on the return journey',
  },
  {
    id: 'proxima-b',
    name: 'Proxima Centauri b',
    kind: 'exoplanet',
    where: 'the nearest star to the Sun, 4.24 light-years away',
    facts: [
      'Proxima b is the closest known planet outside our solar system, orbiting the nearest star — in the zone where liquid water could exist.',
      'It is probably tidally locked: one side in permanent day, one in permanent night, and a ring of eternal twilight between them where the weather might be just right.',
      'Its star is a flare star that periodically blasts it with radiation. If anything lives there, it is tough.',
    ],
    grit: 'Proxima b is the closest other world there is, and it is not easy. One face burns, one freezes, and the star throws tantrums. The habitable part is the thin line between the extremes — a permanent dawn. Some places are livable precisely because they stay on the edge.',
    strength: 'You live in the twilight band and you have made it habitable.',
    caution: 'Tidal lock means one face never sees the other. Turn, occasionally.',
    forward: 'You are the nearest neighbour to something enormous and have learned to live between its extremes. This year, expand the twilight zone — the strip where you actually thrive is wider than you think.',
    transmission: 'One side burns, one side freezes. I live in the dawn.',
    forWho: 'the ones who live between extremes',
  },
  {
    id: 'pulsar',
    name: 'PSR B1919+21',
    kind: 'pulsar — the first one found',
    where: 'about 2,300 light-years away, in Vulpecula',
    facts: [
      'In 1967 a graduate student named Jocelyn Bell noticed a signal repeating every 1.337 seconds, so regular the team half-jokingly labelled it LGM-1: Little Green Men.',
      'It was a neutron star — a dead star’s core, the mass of the Sun packed into a city, spinning and sweeping a radio beam across the sky like a lighthouse.',
      'Some pulsars keep time better than atomic clocks. The Nobel Prize for the discovery went to Bell’s supervisor. She kept working.',
    ],
    grit: 'A pulsar is what remains after a star dies violently: something small, dense, and so regular you could set the universe’s clock by it. And its discoverer was overlooked for the prize, and went on to become one of the most respected figures in the field anyway. Both are the same lesson.',
    strength: 'After the collapse, you became the most reliable thing in the sky.',
    caution: 'Perfect regularity can be mistaken for a machine. Let someone hear the person in the signal.',
    forward: 'You have been through the supernova. What is left is dense, precise, and keeps ticking. This year, let your consistency be the thing people navigate by — and take the credit you were skipped for.',
    transmission: 'Every 1.337 seconds. You could set your life by me.',
    forWho: 'the reliable ones who were overlooked',
  },
  {
    id: 'photon',
    name: 'The Photon',
    kind: 'particle of light',
    where: 'in transit — always',
    facts: [
      'A photon has no mass and travels at the only speed it can: the speed of light. For the photon, no time passes at all — from its point of view it is emitted and absorbed in the same instant, no matter how far it went.',
      'A photon created in the Sun’s core takes tens of thousands of years to random-walk to the surface, then 8 minutes 20 seconds to reach your eye.',
      'Every colour you have ever seen was a photon ending its journey on your retina. That is the only way it stops.',
    ],
    grit: 'The photon crosses the universe and experiences none of the journey — only the arrival. It spends ages fighting its way out of the star that made it, then flies free, and its whole existence resolves into the single moment something finally sees it.',
    strength: 'You are the thing that lets everyone else see. And you do not get tired.',
    caution: 'A photon only counts when it lands. Aim.',
    forward: 'You fought your way out of the core for a long time. That part is done. This year, you are in free flight — let the journey be short in your mind and the landing be exact.',
    transmission: 'Eight minutes from the Sun. No time at all for me.',
    forWho: 'the ones finally out of the core',
  },
  {
    id: 'tardigrade',
    name: 'The Tardigrades of FOTON-M3',
    kind: 'the first animals to survive open space',
    where: 'they went to orbit in 2007 and came back alive',
    facts: [
      'In 2007 a European mission exposed tardigrades — half-millimetre “water bears” — to the vacuum and radiation of open space for ten days. Many survived. Some later laid eggs that hatched normally.',
      'They do it by entering cryptobiosis: expelling almost all their water and shutting their metabolism down to nearly nothing until conditions improve.',
      'They have survived −272 °C, 150 °C, pressures six times the deepest ocean, and every one of Earth’s mass extinctions.',
    ],
    grit: 'The tardigrade is not strong. It is not fast. It has one move: when things become impossible, it becomes almost nothing and waits. Then it wakes up, fully itself, and carries on. It has been doing this for 500 million years.',
    strength: 'You know how to go small, go still, and come back whole. Almost nothing else can.',
    caution: 'Cryptobiosis is for surviving, not for living. Know when the conditions have actually improved and wake up.',
    forward: 'You have survived a season by drying out and waiting. It worked. This year, check the readings — the vacuum may have passed. It is time to rehydrate.',
    transmission: 'I have been to space with no suit. I am fine. How are you?',
    forWho: 'the survivors',
  },
  {
    id: 'betelgeuse',
    name: 'Betelgeuse',
    kind: 'red supergiant star',
    where: 'Orion’s shoulder, about 550 light-years away',
    facts: [
      'Betelgeuse is so large that placed where the Sun is, it would swallow Mercury, Venus, Earth, Mars, and reach nearly to Jupiter.',
      'In late 2019 it dimmed dramatically — the “Great Dimming” — and astronomers wondered if it was about to explode. It had thrown off a cloud of its own material and hidden behind it for a while.',
      'It will go supernova sometime in the next hundred thousand years. When it does, it will be visible in daylight for months. The light that shows us that may already be on its way.',
    ],
    grit: 'Betelgeuse is enormous, unstable, near the end, and one of the most beautiful things in the winter sky. When it dimmed, the whole world looked up worried. It was just shedding. It came back. When it finally goes, it will go brighter than anything.',
    strength: 'Even your dimming makes the world look up.',
    caution: 'Shedding a cloud of yourself to get through a hard patch is fine. Don’t hide behind it longer than the dimming lasts.',
    forward: 'You have had a Great Dimming — a stretch where people wondered if you were done. You were shedding. This year, come back to full brightness and let them recalibrate.',
    transmission: 'I dimmed. Everyone panicked. I was just getting ready.',
    forWho: 'the ones coming back from a dim stretch',
  },
  {
    id: 'pale-blue-dot',
    name: 'The Pale Blue Dot',
    kind: 'a photograph',
    where: 'taken 14 February 1990, from 6 billion km away',
    facts: [
      'As Voyager 1 left the solar system, Carl Sagan persuaded NASA to turn it around for one last photo of home. Earth is a single pixel, less than one pixel across, in a beam of scattered sunlight.',
      'Sagan wrote of it: everyone you have ever heard of lived their entire life on that dot.',
      'It remains the most distant photograph of Earth ever taken.',
    ],
    grit: 'The most powerful image humanity has ever made of itself is one pixel, barely there, in a sunbeam. It was taken on purpose, looking back, right before leaving forever. There is a kind of courage in turning around for one last look.',
    strength: 'You know how to look back without turning back.',
    caution: 'A single pixel holds everything. Do not mistake small for insignificant — in yourself or others.',
    forward: 'You are leaving something behind this year, or you already have. Turn the camera around once. Take the picture. Then keep going.',
    transmission: 'That’s here. That’s home. That’s us. — and I was leaving.',
    forWho: 'the ones looking back before moving on',
  },
  {
    id: 'hubble',
    name: 'The Hubble Space Telescope',
    kind: 'orbiting observatory',
    where: 'low Earth orbit, 540 km up, since 1990',
    facts: [
      'Hubble launched in 1990 with a flaw in its main mirror — ground to the wrong shape by a fraction of the width of a human hair. Its first images were blurry. It was a public embarrassment.',
      'In 1993 astronauts installed corrective optics by hand, in orbit. After that, it gave us the deepest images of the universe ever taken.',
      'The Hubble Ultra Deep Field pointed at a patch of dark sky the size of a grain of sand at arm’s length and found 10,000 galaxies in it.',
    ],
    grit: 'Hubble began as a failure — expensive, famous, and out of focus. It became one of the most important scientific instruments in history because someone flew up and fixed the flaw instead of writing it off. The mistake was real. So was the correction.',
    strength: 'Your early blurry years are not the story. The correction is.',
    caution: 'A flaw a hair’s width off can blur everything. Get the corrective optics installed — it takes a hand, not a rebuild.',
    forward: 'Something in you was ground slightly wrong at the start, and you have been apologising for the blur. This year, install the fix. Then point at the darkest patch of sky you can find and count what’s there.',
    transmission: 'I launched broken. Then I showed you ten thousand galaxies.',
    forWho: 'the ones who fixed the flaw and kept looking',
  },
  {
    id: 'uranus',
    name: 'Uranus',
    kind: 'ice giant',
    where: 'the seventh planet, rolling on its side',
    facts: [
      'Uranus is tipped over 98 degrees — it orbits the Sun rolling on its side, probably knocked over by a giant collision long ago.',
      'As a result each pole gets 42 years of continuous sunlight, then 42 years of darkness.',
      'It was the first planet discovered with a telescope, in 1781 — William Herschel initially thought it was a comet. It had been catalogued as a star at least 17 times before anyone realised it was moving.',
    ],
    grit: 'Uranus got hit hard enough to knock it sideways, and instead of righting itself it just kept going that way, and built forty-year seasons around the new angle. It was mistaken for a star seventeen times before someone noticed it was actually going somewhere.',
    strength: 'You were knocked sideways and turned it into a way of moving.',
    caution: 'Forty-two years of daylight on one side means forty-two of dark on the other. Rotate your attention.',
    forward: 'People have catalogued you as fixed — a background star — more than once. This year, let them notice you are moving. The tilt is not a defect; it is the orbit you built.',
    transmission: 'I roll sideways. I still get around the Sun.',
    forWho: 'the tilted ones',
    lightMinutes: 159.6,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    kind: 'ice giant',
    where: 'the outermost planet, found by mathematics',
    facts: [
      'Neptune was discovered with a pencil before a telescope. In 1846 Urbain Le Verrier calculated where an unseen planet must be from wobbles in Uranus’s orbit; an astronomer pointed a telescope there and found it within one degree, the same night.',
      'It has the fastest winds in the solar system — over 2,000 km/h — on a world that receives a thousandth of the sunlight Earth does.',
      'It completed its first full orbit since discovery in 2011: one Neptune year is 165 of ours.',
    ],
    grit: 'Neptune was known to exist before anyone saw it, because the math of its influence on others was undeniable. It moves almost no light and yet drives the wildest weather anywhere. Its effect was measurable long before it was visible.',
    strength: 'People can tell you are there from the way everything around you moves.',
    caution: 'Being inferred is not the same as being seen. Let someone point the telescope.',
    forward: 'You have been the unseen influence — the wobble everyone attributes to something else. This year, be at the coordinates when they finally look. Within one degree.',
    transmission: 'You found me by my effect on others. Then you looked, and I was there.',
    forWho: 'the felt-but-unseen',
    lightMinutes: 250.1,
  },
  {
    id: 'great-red-spot',
    name: 'The Great Red Spot',
    kind: 'storm on Jupiter',
    where: 'Jupiter’s southern hemisphere, for at least 190 years',
    facts: [
      'The Great Red Spot is a storm larger than Earth that has been raging for at least 190 years — continuously observed since the 1830s, and possibly seen in the 1600s.',
      'Winds at its edge exceed 400 km/h. It rotates counter-clockwise, once every six days.',
      'It is shrinking. It was twice its current size in the 1800s. It may not last forever — but it has outlived everyone who ever pointed a telescope at it.',
    ],
    grit: 'A storm is supposed to blow itself out. This one has been going for two centuries, longer than any human institution watching it. It has changed shape and colour and size, and it has never stopped.',
    strength: 'You have been running longer than the people measuring you.',
    caution: 'Even a 190-year storm shrinks if it stops feeding. Find the current that sustains you.',
    forward: 'You are a storm that was supposed to blow over. It didn’t. This year, don’t worry about the shrinking — worry about the wind that feeds it, and keep that flowing.',
    transmission: 'Two hundred years. Still spinning.',
    forWho: 'the long-running ones',
    lightMinutes: 43.3,
  },
  {
    id: 'saturn-rings',
    name: 'Saturn’s Rings',
    kind: 'ring system',
    where: 'around the sixth planet, impossibly thin',
    facts: [
      'Saturn’s rings span 280,000 km across but in most places are only about 10 metres thick. Scaled to a sheet of paper, they would be thousands of times thinner.',
      'They are almost entirely water ice — countless pieces from dust grains to house-sized boulders, each on its own orbit.',
      'They are probably young — perhaps only 100 million years old — and are slowly raining onto Saturn. In a few hundred million years they may be gone.',
    ],
    grit: 'The most beautiful structure in the solar system is temporary, absurdly thin, and made of nothing but ice and ordinary rules of orbit. It is not permanent. It is not thick. It is the thing everyone remembers.',
    strength: 'You do not have to be permanent or substantial to be the thing people remember.',
    caution: 'Ten metres thick, 280,000 wide: you are spread thin. Some of it is raining down. Consolidate a little.',
    forward: 'You are made of countless small things each on its own orbit, and from a distance they form something unforgettable. This year, accept that this is a season, not a monument — and make it a spectacular one.',
    transmission: 'Ten metres thick. Visible from another planet.',
    forWho: 'the spread-thin and the beautiful',
    lightMinutes: 79.3,
  },
  {
    id: 'trappist-1',
    name: 'TRAPPIST-1',
    kind: 'planetary system',
    where: '40 light-years away, in Aquarius',
    facts: [
      'TRAPPIST-1 is a dim red dwarf barely bigger than Jupiter, with seven Earth-sized planets packed closer to it than Mercury is to the Sun. Three or four are in the habitable zone.',
      'The planets are so close together that from one, the others would appear larger than our Moon — worlds hanging in the sky.',
      'The whole system would fit inside Mercury’s orbit. The star will burn for trillions of years — long after the Sun is gone.',
    ],
    grit: 'TRAPPIST-1 is a small, faint star that nobody would look at twice — and it holds seven worlds in a tight, patient family, and it will outlive our Sun by a factor of a hundred. Being dim is not the same as being unimportant.',
    strength: 'You are small and you hold a whole system together, and you will be here a very long time.',
    caution: 'Seven worlds in a tight orbit tug on each other. Give your people some room — resonance is good; collision is not.',
    forward: 'The bright stars burn out. You were built for the long game. This year, stop comparing your light to the giants and count the worlds you are keeping warm.',
    transmission: 'Faint star, seven planets, trillion-year plan.',
    forWho: 'the quiet ones who hold a family together',
  },
  {
    id: 'dark-matter',
    name: 'Dark Matter',
    kind: 'the invisible scaffolding of galaxies',
    where: 'all around you, in a halo wrapping the whole Milky Way',
    facts: [
      'Galaxies spin so fast they should fly apart. They don’t — because something invisible, five times more massive than all the visible stars and gas, holds them together. We call it dark matter.',
      'It does not emit, absorb, or reflect light. We have never seen it. We know it exists only from what it does to everything else.',
      'About 85% of all the matter in the universe is this. The stars are the minority.',
    ],
    grit: 'The universe’s most important structure is entirely invisible, and it holds every galaxy together without ever being noticed directly. It is known only by its effect. It does not need to be seen to be the reason things stay intact.',
    strength: 'You are the reason things hold together, and you have never needed the credit.',
    caution: 'Invisible support is still support that can be taken for granted. Occasionally, let the rotation curve show.',
    forward: 'You have been the halo — the mass nobody counts that keeps everything from flying apart. This year, understand your own weight. Then decide what deserves to orbit you.',
    transmission: 'You cannot see me. Everything you can see is held by me.',
    forWho: 'the invisible ones holding it together',
  },
  {
    id: 'andromeda',
    name: 'The Andromeda Galaxy',
    kind: 'galaxy',
    where: '2.5 million light-years away, and approaching',
    facts: [
      'Andromeda is the nearest large galaxy and the most distant thing you can see with the naked eye. Its light left it 2.5 million years ago, before humans existed.',
      'It is coming toward us at about 110 km/s. In roughly 4.5 billion years the two galaxies will merge into one.',
      'When they do, almost no stars will collide — space is that empty. The two spirals will simply pass through each other and settle into something new.',
    ],
    grit: 'Two galaxies, a trillion stars each, on a collision course — and the merger will be gentle, because even a galaxy is mostly space. The largest change imaginable is happening at walking pace, and it will not break anything. It will make something.',
    strength: 'You can merge with something enormous without losing a single star.',
    caution: 'Approaching at 110 km/s for four billion years is a long time to be “about to.” Some mergers can start now.',
    forward: 'Something large is approaching you, and it looks like a collision. It is a merger. Almost nothing you are made of will be lost. This year, stop bracing and start combining.',
    transmission: 'I am coming. Nothing will break.',
    forWho: 'the ones facing a big merge',
  },
  {
    id: 'moon',
    name: 'The Moon',
    kind: 'Earth’s only natural satellite',
    where: '384,000 km away, and 3.8 cm farther every year',
    facts: [
      'The Moon was probably born from a catastrophe — a Mars-sized body hitting the young Earth and blasting off the debris that became it.',
      'It is tidally locked: the same face has looked at Earth for billions of years. It is also drifting away, 3.8 cm a year — the distance your fingernails grow.',
      'It stabilises Earth’s tilt. Without it, our seasons would swing chaotically over millions of years. Life here is steadier because it is there.',
    ],
    grit: 'The Moon came from the worst day in Earth’s history, and became the thing that keeps Earth steady. It has kept its face turned toward us for four billion years, asking nothing, holding the seasons in place, drifting away by a fingernail a year and never leaving.',
    strength: 'You came out of a collision and became the thing that steadies everyone.',
    caution: 'Always showing the same face means there is a far side nobody knows. Show it once in a while.',
    forward: 'You are drifting a fingernail farther every year. That is not leaving; it is the shape of a long relationship. This year, keep the tides going, and let someone see the far side.',
    transmission: 'Born in a catastrophe. Keeping your seasons steady ever since.',
    forWho: 'the steadying ones',
    lightMinutes: 8.3,
  },
  {
    id: 'sedna',
    name: 'Sedna',
    kind: 'distant dwarf planet',
    where: 'far beyond the Kuiper Belt, on an 11,400-year orbit',
    facts: [
      'Sedna is one of the most distant objects known in the solar system, on an orbit so long — about 11,400 years — that it has completed less than one loop since the last Ice Age.',
      'It is one of the reddest objects in the solar system, and nobody is quite sure why it is out there. Something big — a passing star, or an undiscovered planet — likely nudged it.',
      'It reaches its closest approach to the Sun in 2076. It will not be this close again for eleven millennia.',
    ],
    grit: 'Sedna is on a journey no human will ever see complete. It was pushed out to the edge of everything by something we still have not identified, and it has been quietly, redly, faithfully coming back this whole time. It arrives in 2076, right on schedule, for a visit nobody alive will fully witness.',
    strength: 'You keep commitments on a timescale most people cannot even imagine.',
    caution: 'Eleven thousand years is patient. Make sure some of your loops close within a lifetime.',
    forward: 'You are on a long orbit, and you have been at the far end of it. You are inbound now. This year, let the inner solar system see some red.',
    transmission: 'Eleven thousand years per lap. Arriving 2076. Don’t wait up.',
    forWho: 'the ones on the longest orbit',
  },
  {
    id: 'iss',
    name: 'The International Space Station',
    kind: 'orbiting laboratory',
    where: '400 km up, going 28,000 km/h',
    facts: [
      'The ISS has been continuously inhabited since November 2000 — every single day for a quarter of a century, someone has lived off the planet.',
      'It circles Earth every 90 minutes. Its crew sees 16 sunrises and 16 sunsets a day.',
      'It was built in orbit by fifteen countries, piece by piece, over a decade — the most expensive single object humans have ever made, and one of the few things we have ever agreed on.',
    ],
    grit: 'The ISS is a thing that should not work: dozens of modules from rival nations, bolted together in vacuum, kept alive by constant maintenance, falling toward Earth forever and missing. It has held a human presence off-world without a single day’s gap for twenty-five years.',
    strength: 'You keep a fragile, complicated thing running every single day, and nobody sees the maintenance.',
    caution: 'Sixteen sunrises a day is exhilarating and exhausting. Sleep on the schedule, not the sunlight.',
    forward: 'You have kept something inhabited without a day off for a very long time. This year, look out the cupola — sixteen times a day, on purpose. The view was the point.',
    transmission: 'Twenty-five years. Not one day empty.',
    forWho: 'the ones who keep the lights on',
  },
  {
    id: 'parker',
    name: 'Parker Solar Probe',
    kind: 'the fastest human-made object',
    where: 'inside the Sun’s corona',
    facts: [
      'On Christmas Eve 2024, Parker Solar Probe flew within 6.1 million km of the Sun’s surface at 690,000 km/h — the closest and fastest any spacecraft has ever gone.',
      'It survives temperatures over 1,000 °C behind a carbon heat shield just 11 cm thick. Behind that shield, its instruments sit at room temperature.',
      'It is the first spacecraft to touch the Sun — to fly through the corona itself.',
    ],
    grit: 'Parker goes into the one place everything else is designed to avoid, and comes out with data. It does not do this by being indestructible. It does it with a thin, exactly-placed shield and the nerve to keep going closer.',
    strength: 'You go closer to the fire than anyone, and you come back with something.',
    caution: 'The shield is eleven centimetres. Keep it pointed at the heat. Turn your back and you cook.',
    forward: 'You have been circling something intense at a distance. This year, plan the close pass — build the shield first, then go in, and bring the measurement back.',
    transmission: 'I touched the Sun. Room temperature in here.',
    forWho: 'the ones who go toward the heat',
    lightMinutes: 0.3,
  },
  {
    id: 'webb',
    name: 'The James Webb Space Telescope',
    kind: 'infrared observatory',
    where: 'L2, 1.5 million km beyond Earth, in permanent shadow',
    facts: [
      'Webb launched on Christmas Day 2021 after 25 years of development, folded up like origami. It unfolded itself in space — 344 single-point failures, any one of which would have ended the mission. Every one worked.',
      'Its sunshield is the size of a tennis court and keeps the telescope at −233 °C so it can see faint infrared light.',
      'It sees light that has travelled more than 13 billion years — galaxies from the universe’s first few hundred million years.',
    ],
    grit: 'Webb was late, over budget, and had 344 separate ways to fail on the way to a place no one could go to fix it. It unfolded perfectly and now spends its life looking at the beginning of time. Some things are worth every delay.',
    strength: 'You took longer than planned and arrived exactly as capable as you were meant to be.',
    caution: '344 single points of failure is a lot to carry. Ask which ones are actually load-bearing.',
    forward: 'You are unfolding, one hinge at a time, in a place nobody can reach to help. Keep going — the deep field is on the other side of the last deployment.',
    transmission: 'Twenty-five years to build. Now I watch the first light.',
    forWho: 'the late and the worth-waiting-for',
  },
  {
    id: 'higgs',
    name: 'The Higgs Field',
    kind: 'the field that gives mass',
    where: 'filling all of space, including this sentence',
    facts: [
      'The Higgs field fills the entire universe. Particles that interact with it strongly are heavy; those that don’t, like the photon, are massless. It is why anything weighs anything.',
      'It was proposed in 1964 and confirmed in 2012 at CERN, when the Large Hadron Collider found its particle. Peter Higgs waited 48 years to be proven right.',
      'Without it, electrons would have no mass, atoms could not form, and there would be nothing here to read this.',
    ],
    grit: 'The Higgs field is the reason substance exists. It was an idea on paper for almost half a century — unfashionable, unconfirmed — and its author waited nearly his entire career to see it found. It was there the whole time, giving everything weight.',
    strength: 'You give the things around you their substance. It has always been true, whether or not it was confirmed.',
    caution: 'Forty-eight years is a long wait for validation. Do not make your worth contingent on the collider.',
    forward: 'You have been an unproven field for a while — the reason things have weight, without the press conference. This year, understand: the confirmation is a formality. The mass was always yours to give.',
    transmission: 'I have been here since the beginning. You just proved it in 2012.',
    forWho: 'the ones who give everything else its weight',
  },
  {
    id: 'kepler-16b',
    name: 'Kepler-16b',
    kind: 'circumbinary exoplanet',
    where: '245 light-years away, orbiting two suns',
    facts: [
      'Kepler-16b was the first planet confirmed to orbit two stars at once. From its surface, two suns would rise and set — like Tatooine, which is exactly what everyone called it.',
      'The two stars orbit each other every 41 days; the planet circles the pair every 229 days. The math said this configuration should be unstable. It is not.',
      'It is a cold gas giant, roughly Saturn-sized, keeping a steady orbit around a system that is itself in constant motion.',
    ],
    grit: 'Kepler-16b holds a stable orbit around two stars that are themselves spinning around each other. Everyone assumed that kind of arrangement would fly apart. It does not. It has found the one path that works around a centre that never stops moving.',
    strength: 'You keep a steady course around a centre that is itself unstable.',
    caution: 'Two suns means twice the light and twice the pull. Know which one you are actually orbiting.',
    forward: 'You are orbiting two things that are orbiting each other — a job and a family, two parents, two lives. The theory says it can’t be stable. You are the proof it can. This year, trust the orbit.',
    transmission: 'Two suns. One stable orbit. Told you it would work.',
    forWho: 'the ones balancing two centres',
  },
];

export const CATALOG_SIZE = CATALOG.length;
