// Generated from the image manifest — source, credit and license for every
// bundled destination image. Images live in ../img/<id>.jpg (served same-origin
// so issuing a card never contacts a third party).

export const IMAGE_CREDITS = {
  'andromeda': { title: 'Andromeda Galaxy', credit: 'NASA/JPL/California Institute of Technology', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA04921' },
  'betelgeuse': { title: 'Betelgeuse captured by ALMA', credit: 'ALMA (ESO/NAOJ/NRAO) / E. O’Gorman / P. Kervella', license: 'CC BY 4.0', source: 'https://commons.wikimedia.org/wiki/File:Betelgeuse_captured_by_ALMA.jpg' },
  'bootes-void': { title: 'Hubble ultra deep field.jpg', credit: 'NASA / ESA / S. Beckwith (STScI) and the HUDF Team', license: 'Public domain (NASA/ESA)', source: 'https://commons.wikimedia.org/wiki/File:Hubble_ultra_deep_field.jpg' },
  'ceres': { title: 'Occator on Ceres Limb', credit: 'NASA/JPL-Caltech/UCLA/MPS/DLR/IDA', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA21078' },
  'cmb': { title: 'Polarization of the Cosmic Microwave Background', credit: 'ESA/Planck Collaboration', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA18916' },
  'dark-matter': { title: 'Dark Matter Core Defies Explanation', credit: 'GSFC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/GSFC_20171208_Archive_e001774' },
  'enceladus': { title: 'Enceladus Plume', credit: 'NASA/JPL/University of Arizona', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA06443' },
  'europa': { title: 'Europa Plumes Located near Warm Spot on Europa', credit: 'NASA/ESA/W. Sparks STScI/USGS Astrogeology Science Center', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA21444' },
  'great-red-spot': { title: 'Jupiter\'s Great Red Spot, Spotted', credit: 'Enhanced Image by Gerald Eichstadt and Sean Doran (CC BY-NC-SA) based on images provided Courtesy of NASA/JPL-Caltech/SwRI/MSSS', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA21985' },
  'halley': { title: 'Comet Halley', credit: 'NASA/ESA/Giotto Project', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA17485' },
  'higgs': { title: 'CMS Higgs-event.jpg', credit: 'CERN / CMS Collaboration (CC BY-SA 3.0)', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:CMS_Higgs-event.jpg' },
  'hubble': { title: 'Onboard view from STS-61 of the Hubble Space Telescope and moon together', credit: 'JSC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/sts061-57-021' },
  'io': { title: 'Galileo Last View of Tvashtar, Io', credit: 'NASA/JPL/University of Arizona', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA03529' },
  'iss': { title: 'International Space Station after undocking of STS-132.jpg', credit: 'NASA, STS-132 crew', license: 'Public domain (NASA)', source: 'https://commons.wikimedia.org/wiki/File:International_Space_Station_after_undocking_of_STS-132.jpg' },
  'kepler-16b': { title: 'Three Eclipsing Bodies Artist Concept', credit: 'NASA/JPL-Caltech', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA14725' },
  'mercury': { title: 'Happy Little Crater on Mercury', credit: 'GSFC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/GSFC_20171208_Archive_e001625' },
  'moon': { title: 'FullMoon2010.jpg', credit: 'Gregory H. Revera', license: 'CC BY-SA 3.0', source: 'https://commons.wikimedia.org/wiki/File:FullMoon2010.jpg' },
  'muon': { title: 'The aurora borealis blankets the Earth', credit: 'JSC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/iss072e159172' },
  'neptune': { title: 'PIA01492', credit: 'NASA/JPL', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA01492' },
  'neutrino': { title: 'New Hubble Observations of Supernova 1987A Trace Shock Wave', credit: 'GSFC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/GSFC_20171208_Archive_e001986' },
  'opportunity': { title: 'Mars Rover Opportunity at Rock Abrasion Target Potts', credit: 'NASA/JPL-Caltech', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA20285' },
  'oumuamua': { title: '\'Oumuamua Races Toward Outskirts of Solar System (Artist\'s Concept)', credit: 'NASA/ESA/STScI', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA22357' },
  'pale-blue-dot': { title: 'Pale Blue Dot Revisited', credit: 'NASA/JPL-Caltech', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA23645' },
  'parker': { title: 'Parker Solar Probe', credit: 'NASA / Johns Hopkins APL / Steve Gribben', license: 'Public domain (NASA)', source: 'https://commons.wikimedia.org/wiki/File:Parker_Solar_Probe.jpg' },
  'photon': { title: ' Image of Sun From NASA\'s Solar Dynamics Observatory', credit: 'NASA/GSFC/Solar Dynamics Observatory', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA26681' },
  'pluto': { title: 'Pluto Methane Snowcaps on the Edge of Darkness context', credit: 'NASA/Johns Hopkins University Applied Physics Laboratory/Southwest Research Institute', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA21025' },
  'proxima-b': { title: 'Hubble\'s Best Image of Alpha Centauri A and B', credit: 'GSFC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/GSFC_20171208_Archive_e000214' },
  'pulsar': { title: 'Most Detailed Image of the Crab Nebula', credit: 'NASA/ESA/JPL/Arizona State Univ.', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA03606' },
  'quantum-vacuum': { title: 'Webb_first_deep_field_SMACS_0723', credit: 'STScI', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/webb_first_deep_field' },
  'saturn-rings': { title: 'The Edge of the Night', credit: 'NASA/JPL-Caltech/Space Science Institute', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA17199' },
  'sedna': { title: 'Artist Concept of Sedna', credit: 'NASA/JPL-Caltech', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA05566' },
  'sgr-a': { title: 'Stars Gather in Downtown Milky Way', credit: 'NASA/JPL-Caltech', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA13932' },
  'tardigrade': { title: 'SEM image of Milnesium tardigradum in active state - journal.pone.0045682.g001-2.png', credit: 'Schokraie E et al., PLOS ONE (CC BY 2.5)', license: 'CC BY 2.5', source: 'https://commons.wikimedia.org/wiki/File:SEM_image_of_Milnesium_tardigradum_in_active_state_-_journal.pone.0045682.g001-2.png' },
  'titan': { title: 'Behold Belet', credit: 'NASA/JPL/Space Science Institute', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA12615' },
  'trappist-1': { title: 'TRAPPIST-1 Planet Lineup', credit: 'NASA/JPL-Caltech', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA21422' },
  'triton': { title: 'Triton Mosaic', credit: 'NASA/JPL', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA02235' },
  'uranus': { title: 'Uranus2.jpg', credit: 'NASA / JPL, Voyager 2', license: 'Public domain (NASA)', source: 'https://commons.wikimedia.org/wiki/File:Uranus2.jpg' },
  'venus': { title: 'Global view of Venus from Magellan, Pioneer, and Venera data', credit: 'JSC', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/S91-50688' },
  'voyager1': { title: 'Voyager Captures Sounds of Interstellar Space', credit: 'NASA/JPL-Caltech/University of Iowa', license: 'Public domain (NASA)', source: 'https://images.nasa.gov/details/PIA17045' },
  'webb': { title: 'James Webb Space Telescope Revealed (26764527271)', credit: 'NASA / Chris Gunn', license: 'Public domain (NASA)', source: 'https://commons.wikimedia.org/wiki/File:James_Webb_Space_Telescope_Revealed_(26764527271).jpg' },
};
